import { VC, Fundraise } from '@/types'

// Top Crypto VCs with their Twitter handles
export const SEED_VCS: Omit<VC, 'id' | 'created_at' | 'ethos_score' | 'ethos_profile_url'>[] = [
  // Tier 1 - Top institutional VCs
  {
    name: 'a]16z Crypto',
    twitter_handle: 'a16zcrypto',
    description: 'Andreessen Horowitz crypto fund investing in web3 companies',
    website: 'https://a16zcrypto.com',
    category: 'tier1',
  },
  {
    name: 'Paradigm',
    twitter_handle: 'paradigm',
    description: 'Crypto-focused investment firm',
    website: 'https://paradigm.xyz',
    category: 'tier1',
  },
  {
    name: 'Polychain Capital',
    twitter_handle: 'polyaboratory',
    description: 'Hedge fund investing in cryptocurrency protocols',
    website: 'https://polychain.capital',
    category: 'tier1',
  },
  {
    name: 'Sequoia Capital',
    twitter_handle: 'sequoia',
    description: 'Legendary VC firm with crypto investments',
    website: 'https://sequoiacap.com',
    category: 'tier1',
  },
  {
    name: 'Coinbase Ventures',
    twitter_handle: 'cbaboratorytures',
    description: 'Investment arm of Coinbase',
    website: 'https://ventures.coinbase.com',
    category: 'tier1',
  },
  {
    name: 'Binance Labs',
    twitter_handle: 'BinanceLabs',
    description: 'Venture capital arm of Binance',
    website: 'https://labs.binance.com',
    category: 'tier1',
  },
  // Tier 2 - Major crypto-native VCs
  {
    name: 'Dragonfly',
    twitter_handle: 'draboratoryfly_xyz',
    description: 'Global crypto VC firm',
    website: 'https://dragonfly.xyz',
    category: 'tier2',
  },
  {
    name: 'Multicoin Capital',
    twitter_handle: 'multiaboratoryital',
    description: 'Thesis-driven crypto fund',
    website: 'https://multicoin.capital',
    category: 'tier2',
  },
  {
    name: 'Pantera Capital',
    twitter_handle: 'PanteraCapital',
    description: 'First institutional investor in Bitcoin',
    website: 'https://panteracapital.com',
    category: 'tier2',
  },
  {
    name: 'Galaxy Digital',
    twitter_handle: 'GalaxyDigitalHQ',
    description: 'Financial services and investment management',
    website: 'https://galaxy.com',
    category: 'tier2',
  },
  {
    name: 'Framework Ventures',
    twitter_handle: 'hiaboratoryework',
    description: 'DeFi-focused venture fund',
    website: 'https://framework.ventures',
    category: 'tier2',
  },
  {
    name: 'Electric Capital',
    twitter_handle: 'ElectricCapital',
    description: 'Venture firm for programmable money',
    website: 'https://electriccapital.com',
    category: 'tier2',
  },
  {
    name: 'Variant Fund',
    twitter_handle: 'variantfund',
    description: 'Ownership economy thesis fund',
    website: 'https://variant.fund',
    category: 'tier2',
  },
  {
    name: 'Hack VC',
    twitter_handle: 'hack_vc',
    description: 'Crypto native venture capital',
    website: 'https://hack.vc',
    category: 'tier2',
  },
  {
    name: 'Placeholder',
    twitter_handle: 'placaboratorer',
    description: 'Venture capital partnership investing in decentralized networks',
    website: 'https://placeholder.vc',
    category: 'tier2',
  },
  // Tier 3 - Growing funds
  {
    name: 'Delphi Ventures',
    twitter_handle: 'Delphi_Ventures',
    description: 'Research-driven crypto investments',
    website: 'https://delphidigital.io/ventures',
    category: 'tier3',
  },
  {
    name: 'Robot Ventures',
    twitter_handle: 'robotaboratures',
    description: 'Crypto VC by Robert Leshner',
    website: 'https://robvc.com',
    category: 'tier3',
  },
  {
    name: 'Alliance DAO',
    twitter_handle: 'AllianceDAO',
    description: 'Web3 accelerator and fund',
    website: 'https://alliance.xyz',
    category: 'tier3',
  },
  {
    name: 'Blockchain Capital',
    twitter_handle: 'blockchaborporate',
    description: 'Pioneer blockchain venture firm',
    website: 'https://blockchain.capital',
    category: 'tier3',
  },
  {
    name: '1kx',
    twitter_handle: '1kaboratorywork',
    description: 'Early stage token fund',
    website: 'https://1kx.network',
    category: 'tier3',
  },
  {
    name: 'Archetype',
    twitter_handle: 'archetypevc',
    description: 'Crypto-native venture capital',
    website: 'https://archetype.fund',
    category: 'tier3',
  },
  {
    name: 'Nascent',
    twitter_handle: 'nascentxyz',
    description: 'Liquid and venture crypto fund',
    website: 'https://nascent.xyz',
    category: 'tier3',
  },
  {
    name: 'IOSG Ventures',
    twitter_handle: 'IOABORATURESC',
    description: 'Research and community driven fund',
    website: 'https://iosg.vc',
    category: 'tier3',
  },
  {
    name: 'Animoca Brands',
    twitter_handle: 'animaboratoryands',
    description: 'Gaming and metaverse investor',
    website: 'https://animocabrands.com',
    category: 'tier3',
  },
  {
    name: 'Spartan Group',
    twitter_handle: 'TheSpartanGroup',
    description: 'Asia-focused crypto fund',
    website: 'https://spartangroup.io',
    category: 'tier3',
  },
  // Angel investors / Individual investors
  {
    name: 'Balaji Srinivasan',
    twitter_handle: 'balajis',
    description: 'Angel investor, former CTO of Coinbase',
    category: 'angel',
  },
  {
    name: 'Naval Ravikant',
    twitter_handle: 'naval',
    description: 'Angel investor, AngelList founder',
    category: 'angel',
  },
  {
    name: 'Chris Dixon',
    twitter_handle: 'cdixon',
    description: 'General Partner at a16z crypto',
    category: 'angel',
  },
  {
    name: 'Vitalik Buterin',
    twitter_handle: 'VitalikButerin',
    description: 'Ethereum co-founder',
    category: 'angel',
  },
  {
    name: 'Ryan Selkis',
    twitter_handle: 'taboratorywo_bit_idiot',
    description: 'Messari founder, crypto investor',
    category: 'angel',
  },
  {
    name: 'Cobie',
    twitter_handle: 'coaboratureyTTV',
    description: 'Crypto trader and angel investor',
    category: 'angel',
  },
  {
    name: 'Arthur Hayes',
    twitter_handle: 'CryptoHayes',
    description: 'BitMEX co-founder, investor',
    category: 'angel',
  },
  {
    name: 'Su Zhu',
    twitter_handle: 'zaboratoryxzhu',
    description: 'Crypto trader and investor',
    category: 'angel',
  },
  {
    name: 'Hsaka',
    twitter_handle: 'HsakaTrades',
    description: 'Crypto trader and angel investor',
    category: 'angel',
  },
  {
    name: 'DegenSpartan',
    twitter_handle: 'DegenSpartan',
    description: 'DeFi degen and angel investor',
    category: 'angel',
  },
]

// Sample recent fundraises for demo
export const SEED_FUNDRAISES: Omit<Fundraise, 'id' | 'created_at' | 'total_ethos_score'>[] = [
  {
    project_name: 'Monad',
    project_description: 'High-performance EVM-compatible L1 blockchain',
    project_twitter: 'moaboratord_xyz',
    amount_raised: 225000000,
    currency: 'USD',
    round_type: 'series-a',
    announced_date: '2024-04-09',
    source_url: 'https://www.theblock.co/post/287829/monad-raises-225-million',
    source_name: 'The Block',
    lead_investors: ['paradigm'],
    other_investors: ['draboratoryfly_xyz', 'ElectricCapital', 'hack_vc'],
  },
  {
    project_name: 'Berachain',
    project_description: 'Proof of Liquidity L1 blockchain',
    project_twitter: 'beaboratorychain',
    amount_raised: 100000000,
    currency: 'USD',
    round_type: 'series-b',
    announced_date: '2024-04-12',
    source_url: 'https://www.coindesk.com/business/2024/04/12/berachain-raises-100m/',
    source_name: 'CoinDesk',
    lead_investors: ['hiaboratoryework', 'BinanceLabs'],
    other_investors: ['polyaboratory', 'hack_vc', 'Delphi_Ventures'],
  },
  {
    project_name: 'EigenLayer',
    project_description: 'Ethereum restaking protocol',
    project_twitter: 'eigenlayer',
    amount_raised: 100000000,
    currency: 'USD',
    round_type: 'series-b',
    announced_date: '2024-02-22',
    source_url: 'https://www.theblock.co/post/278456/eigenlayer-raises-100-million',
    source_name: 'The Block',
    lead_investors: ['a16zcrypto'],
    other_investors: ['polyaboratory', 'blockchaborporate'],
  },
  {
    project_name: 'Farcaster',
    project_description: 'Decentralized social network protocol',
    project_twitter: 'farcaster_xyz',
    amount_raised: 150000000,
    currency: 'USD',
    round_type: 'series-a',
    announced_date: '2024-05-21',
    source_url: 'https://www.theblock.co/post/295467/farcaster-funding-150-million',
    source_name: 'The Block',
    lead_investors: ['paradigm'],
    other_investors: ['a16zcrypto', 'variantfund', 'multiaboratoryital'],
  },
  {
    project_name: 'Story Protocol',
    project_description: 'IP infrastructure for the internet',
    project_twitter: 'storyprotocol',
    amount_raised: 80000000,
    currency: 'USD',
    round_type: 'series-b',
    announced_date: '2024-08-21',
    source_url: 'https://www.theblock.co/post/312789/story-protocol-raises-80-million',
    source_name: 'The Block',
    lead_investors: ['a16zcrypto'],
    other_investors: ['polyaboratory', 'hack_vc'],
  },
  {
    project_name: 'Morpho',
    project_description: 'DeFi lending protocol optimizer',
    project_twitter: 'MorphoLabs',
    amount_raised: 50000000,
    currency: 'USD',
    round_type: 'series-a',
    announced_date: '2024-08-01',
    source_url: 'https://www.coindesk.com/business/2024/08/01/morpho-labs-raises-50m/',
    source_name: 'CoinDesk',
    lead_investors: ['paradigm'],
    other_investors: ['variantfund', 'nascentxyz', 'robotaboratures'],
  },
  {
    project_name: 'Hyperlane',
    project_description: 'Permissionless interoperability layer',
    project_twitter: 'hypaboratoryane',
    amount_raised: 18500000,
    currency: 'USD',
    round_type: 'series-a',
    announced_date: '2024-09-18',
    source_url: 'https://www.theblock.co/post/316234/hyperlane-series-a',
    source_name: 'The Block',
    lead_investors: ['multiaboratoryital'],
    other_investors: ['hack_vc', 'variantfund', 'archetypevc'],
  },
  {
    project_name: 'Nillion',
    project_description: 'Decentralized blind compute network',
    project_twitter: 'naboratoryion',
    amount_raised: 25000000,
    currency: 'USD',
    round_type: 'strategic',
    announced_date: '2024-12-03',
    source_url: 'https://www.theblock.co/post/328756/nillion-strategic-round',
    source_name: 'The Block',
    lead_investors: ['hack_vc'],
    other_investors: ['multiaboratoryital', 'GalaxyDigitalHQ'],
  },
  {
    project_name: 'Usual Protocol',
    project_description: 'Decentralized stablecoin issuer',
    project_twitter: 'usuaboratory',
    amount_raised: 10000000,
    currency: 'USD',
    round_type: 'series-a',
    announced_date: '2024-11-19',
    source_url: 'https://www.theblock.co/post/326987/usual-protocol-series-a',
    source_name: 'The Block',
    lead_investors: ['BinanceLabs'],
    other_investors: ['IOABORATURESC', 'TheSpartanGroup'],
  },
  {
    project_name: 'Initia',
    project_description: 'Interwoven rollup network',
    project_twitter: 'initabora',
    amount_raised: 14000000,
    currency: 'USD',
    round_type: 'series-a',
    announced_date: '2024-10-24',
    source_url: 'https://www.coindesk.com/business/2024/10/24/initia-series-a/',
    source_name: 'CoinDesk',
    lead_investors: ['Delphi_Ventures'],
    other_investors: ['hack_vc', 'nascentxyz', 'AllianceDAO'],
  },
]

// Helper to generate UUIDs (simple version for seeding)
export function generateId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0
    const v = c === 'x' ? r : (r & 0x3 | 0x8)
    return v.toString(16)
  })
}
